<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Employee::create([
            'name'             => 'مهند الشوا',
            'Administration'   => 'الموارد البشرية والسؤون الإدارية',
            'job_num'          => 1,
            'department'       => 'إدارة الأسطول',
            'position'         => 'مشرف الأسطول',
            'direct_maneger'   => 'هبة مناع',
            'start_date'       => '2024/02/04',
            'work_site'        => 'المركز الإداري',
            'sheft'            => 'صباحي',
            // qr_token is auto-generated by Employee::booted() now, no need to seed it.
            'card_id'          => '5A:23:A0:AA'
        ]);

        Employee::create([
            'name'             => 'أمير السيد',
            'Administration'   => 'التسويق ',
            'job_num'          => 2,
            'position'         => 'قائد فريق',
            'direct_maneger'   => 'أمير عقاد',
            'start_date'       => '2024/02/04',
            'work_site'        => 'المركز الإداري',
            'sheft'            => 'صباحي',
            'phone_num'        => '0987654321',
            'card_id'          => '5A:1F:58:AA'
        ]);
    }
}
